### PR TITLE
Update 1.21.x + NeoForge

### PR DESCRIPTION
**Pull request by Riflusso**
Actually fully migrated to NeoForge and updated to 1.21.x #98
P.S: I don't know how to reimplement Tooltips in CatmullRomWidget like at previous versions

### CODE REVIEW

**Comment by Kloytz** [comment]
Does version 0.9.4 works for 1.21.1?

**Comment by Riflusso** [comment]
Nope, just 0.9.3 works well with 1.21.1

**Comment by Kloytz** [comment]
image
This one?

**Comment by Riflusso** [comment]
Nope, @Schauweg need to revert Update 1.21.2+ commit and build mod for 1.21.1, as I see, he haven't published it yet

**Comment by Riflusso** [comment]
Or you can download it from my releases https://github.com/Riflusso/Smooth-Swapping/releases/tag/0.9.3%2B1.21

**Comment by Kloytz** [comment]
ehmm thanks!

**Pull request merged**
